git:
  commit: true
  commitMessage: "chore(release): ${version}"
  tag: true
  tagName: "v${version}"
  requireCleanWorkingDir: false
  push: true

github:
  release: false

npm:
  publish: false

hooks:
  before:init: "pnpm run build && pnpm run package"
  after:bump: "echo '✅ Version bumped to ${version}'"
  after:release: "echo '🚀 Released ${version} to GitHub'"
